### ISSUE TITLE
ServerAPI Startup

### ISSUE THREAD

**Issue by GamingMineblox** [BenChaliah/Arbitrium-RAT#5] opened 2021-03-03 17:32 UTC
Whenever I run `./runserver.sh` it tells me that the server is running, but when I run `screen -x` there is no output. The server closes as soon as it starts up. When I modify the `runserver.sh` to run `screen -x` after it says the following: 

`There are several suitable screens on:
        3614.initproxy  (03/03/21 17:18:23)     (Detached)
        3611.main       (03/03/21 17:18:23)     (Detached)
        3595.initproxy  (03/03/21 17:17:54)     (Detached)
        3550.initproxy  (03/03/21 17:14:59)     (Detached)
        3465.initproxy  (03/03/21 17:08:56)     (Detached)
        3362.initproxy  (03/03/21 17:02:32)     (Detached)
        2063.initproxy  (03/03/21 16:04:11)     (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.`

But when I run the command after the script (`./runserver.sh`) it says there are no screens to attach.
How do I fix this issue? The server is unable to start or crashes on boot and I can't figure out why.

**Comment by GamingMineblox** [comment] 2021-03-03 17:48
Okay so I was able to fix the issue for the most part. The ServerAPI can startup correctly and it stays on.

But now when i try to login I get the following error:
![image](https://user-images.githubusercontent.com/42892277/109848664-cd635880-7c50-11eb-8657-d886eee9a272.png)

I think it has to do something with the console error logger. But I can't figure out how to fix it.

**Comment by BenChaliah** [comment] 2021-03-05 17:04
Make sure python2.7 is installed (run `python2.7` in the terminal), then install required libraries `pip2 install flask flask_cors requests pyjwt`.
To debug the server just run `python2.7 main.py` and check whether you can start the server, if so then kill it and use `runserver.sh`

**Comment by GamingMineblox** [comment] 2021-03-06 17:35
Hello again, 

I have python2.7 installed, but for some reason pip2 isn't installed.
I've tried installing it with `get-pip.py` but that isn't supported for Python 2.7
I'm using Ubuntu 20.04 and can't find any valid pip2 package. Only Python 3.X pip packages

**Comment by GamingMineblox** [comment] 2021-03-06 17:47
Okay so I got the main.py working now. It seems like on every installation I tried the port was already in use!
So my question is as followed: Is it possible to use a different port than port ``80``?
I don't want to miss anything as my friends knew I was going to do some sort of prank on them.

I want to use NGINX for the web server (as I'm more familiar with NGINX and want to run other web-applications on it too)

**Comment by BenChaliah** [comment] 2021-03-06 17:55
yes, you can change port by changing in ligne 440 of [main.py](https://github.com/BenChaliah/Arbitrium-RAT/blob/main/ServerAPI/main.py#L440), but then you need to use `setAPI_FQDN.sh` in the WebApp repo not the one in this repo in order to set the new serveAPI fqdn in the control panel. since the issue isn't related to the project I'll be closing it, but if you have another question you can email me directly.

**Closed** 2021-03-06 17:55 UTC
